export default {
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
  EMPTY_CART: 'EMPTY_CART',
  CREATE_NEW_ORDER_PENDING: 'CREATE_NEW_ORDER_PENDING',
  CREATE_NEW_ORDER_SUCCESS: 'CREATE_NEW_ORDER_SUCCESS',
  CREATE_NEW_ORDER_ERROR: 'CREATE_NEW_ORDER_ERROR',
  VALIDATE_CUSTOMER_INFO: "VALIDATE_CUSTOMER_INFO",
  INVALIDATE_CUSTOMER_INFO: "INVALIDATE_CUSTOMER_INFO",
  FETCH_MY_ORDER: "FETCH_MY_ORDER",
  FETCH_CART_PENDING: 'FETCH_CART_PENDING',
};
